name: Create Release

on:
  workflow_dispatch

jobs:
  create-release:
    name: "Create My Release"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: dir
      run: |
        dir > mydir.txt
        
    - name: compress
      run: |
        Compress-Archive -Path .\mydir.txt -DestinationPath .\mydir.zip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: pleasework
        # A file, directory or wildcard pattern that describes what to upload
        path: mydir.zip
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 90

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
      with:
        tag_name: "v8.0.0"
        release_name: "mydir-draft-v8.0.0"
        draft: true
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./mydir.zip
        asset_name: mydir.zip
        asset_content_type: application/zip
