# The goal of this workflow is to trigger on a PR into the main branch, but only for the App1 project
# I'm not sure it is possible to specific an "on: pull_request" and specify both branch and path

name: PR into Main for App 1

# I don't think this is going to work as expected. I think it will trigger on either condition.
on:
  pull_request:
    branches:
      - main
    paths:
      - 'app1/**' # Hoping this detects any changes under the App1 folder, so when I PR to main this triggers.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  say-hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Hello World
      - name: Hello World
        run: echo "Hello World"
