# The goal of this workflow is to trigger on a push into the main branch, but only for the App1 project

name: Push into Main for App 1

on:
  push:
    branches:
      - main
    paths:
      - 'app1/**' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  say-hello-push-to-main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Hello World - Push to Main
      - name: Hello World Push To Main
        run: echo "Hello World Push To Main"
      
      # Echo env variables
      - name: echo env variables
        run: |
            echo "${{ env.GITHUB_EVENT_NAME }}"
            echo "${{ env.GITHUB_EVENT_PATH }}"
