####################################################################################################
# NAME: Simple Manual Workflow - Three environments
#
# DESCRIPTION:
# I am a simple manual workflow that will run jobs in three different environments
####################################################################################################

name: Simple Manual Workflow - Three Env

on:
  workflow_dispatch:
    
jobs:
  # Job name
  job-dev:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # this job should only run on DEV env
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Simple Run Command
        run: |
          echo "Hi! I'm running in the DEV env."
            
  # Job Name
  job-qa:
      
    runs-on: ubuntu-latest
    needs:
      - job-dev
    environment: QA
      
    steps:
      
      - name: Simple Run Command
        run: |
          echo "Hi! I'm running in the QA env."
      
  # Job Name
  job-prod:
    
    runs-on: ubuntu-latest
    needs:
      - job-qa
    environment: PROD
      
    steps:
      
      - name: Simple Run Command
        run: |
          echo "Hi! I'm running in the PROD env."
