# TODO: Description

name: Simple Manual Workflow

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of Person'
        required: true
        default: 'Jane Doe'
      home:
        description: 'Person Location'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  say-hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #Say Hello
      - name: Time To Say Hello
        run: |
          echo "Hello ${{ github.event.inputs.name}}!"
          echo "You live in ${{ github.event.inputs.home}}!"

      # Create a file
      - name: Create a file
        run: | 
          echo "Line One" >> myoutput.txt
          echo "Line Two" >> myoutput.txt
          
         
      # Upload build artifact to the workflow
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          # Artifact name
          name: buildartifacts # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: myoutput.txt
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: warn # optional, default is warn
          retention-days: 90 # optional

      # Create a second file
      - name: Create a second file
        run: | 
          echo "Line Three" >> myoutput2.txt
          echo "Line Four" >> myoutput2.txt
          
      # Upload build artifact to the workflow
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          # Artifact name
          name: buildartifacts2 # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: myoutput2.txt
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: warn # optional, default is warn
          retention-days: 90 # optional
